services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G
    volumes:
      - ./lavalink/application.yaml:/opt/Lavalink/application.yml
      - ./lavalink/plugins/:/opt/Lavalink/plugins/
    networks:
      - lavalink
    ports:
      - "2333:2333"
  cen-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cen-bot
    restart: unless-stopped
    volumes:
      - ./cen-bot:/app
      - ./logs:/app/logs
    networks:
      - lavalink
    ports:
      - "8080:8080"
    depends_on:
      - lavalink
networks:
  lavalink:
    name: lavalink
