services:
  lavalink:
    container_name: lavalink-dev

  bot:
    container_name: bot-dev
    env_file:
      - .env.local
      - .env.development
    environment:
      - NODE_ENV=dev
    volumes:
      - ./utils:/app/utils
      - ./cogs:/app/cogs
      - ./logs:/app/logs
      - ./logging.yml:/app/logging.yml

networks:
  lavalink:
    name: lavalink-dev