---
version: 1
formatters:
  client:
    format: '%(asctime)s | discord         : %(levelname)-8s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  default: 
    format: '%(asctime)s | %(name)-16s: %(levelname)-8s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers: 
  bot: 
    class: logging.handlers.TimedRotatingFileHandler
    formatter: default
    filename: LOG.log
    when: W6
    backupCount: 3
    encoding: UTF-8
    level: DEBUG
  bot_console:
    class: logging.StreamHandler
    formatter: default
    level: INFO
    stream: ext://sys.stdout
  client:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: client
    filename: LOG.log
    when: W6
    backupCount: 3
    encoding: UTF-8
    level: DEBUG
  client_console:
    class: logging.StreamHandler
    formatter: client
    level: INFO
    stream: ext://sys.stdout
loggers:
  discord:
    handlers: [client, client_console]
    level: INFO
    propogate: false
  CENBot: 
    handlers: [bot, bot_console]
    level: DEBUG
    propogate: false
  CENBot.admin:
    level: DEBUG
    propogate: true
  CENBot.easter:
    level: DEBUG
    propogate: true
  CENBot.logging:
    level: DEBUG
    propogate: true
  CENBot.radio:
    level: DEBUG
    propogate: true
  CENBot.twitch:
    level: DEBUG
    propogate: true
  CENBot.utility:
    level: DEBUG
    propogate: true
  CENBot.welcome:
    level: DEBUG
    propogate: true
  CENBot.xp:
    level: DEBUG
    propogate: true
  CENBot.youtube:
    level: DEBUG
    propogate: true