---
version: 1
formatters:
  default: 
    format: '%(asctime)s | %(levelname)-8s | %(name)s : %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers: 
  bot: 
    class: logging.handlers.TimedRotatingFileHandler
    formatter: default
    filename: logs/bot.log
    when: W6
    backupCount: 3
    encoding: UTF-8
    level: DEBUG
  bot_console:
    class: logging.StreamHandler
    formatter: default
    level: INFO
    stream: ext://sys.stdout
loggers:
  discord:
    handlers: [bot, bot_console]
    level: DEBUG
    propogate: false
  CENBot: 
    handlers: [bot, bot_console]
    level: DEBUG
    propogate: false
  CENBot.admin:
    level: DEBUG
    propogate: true
  CENBot.easter:
    level: DEBUG
    propogate: true
  CENBot.guild:
    level: DEBUG
    propogate: true
  CENBot.internal:
    level: DEBUG
    propogate: true
  CENBot.moderation:
    level: DEBUG
    propogate: true
  CENBot.radio:
    level: DEBUG
    propogate: true
  CENBot.twitch:
    level: DEBUG
    propogate: true
  CENBot.utility:
    level: DEBUG
    propogate: true
  CENBot.welcome:
    level: DEBUG
    propogate: true
  CENBot.xp:
    level: DEBUG
    propogate: true
  CENBot.youtube:
    level: DEBUG
    propogate: true